name: CI/CD Security Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Installer les dépendances
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Exécuter les tests
        run: |
          source venv/bin/activate
          python -m unittest discover

  security:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Analyser avec SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=zaheryamak
            -Dsonar.projectKey=zaheryamak_tp-ci-cd
            -Dsonar.sources=.
            -Dsonar.host.url=https://sonarcloud.io

    - name: Scanner avec Snyk (Python)
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK }}
      with:
        args: --all-projects


  deploy:
    needs: security
    runs-on: ubuntu-latest
    steps:
      - name: Déclencher le déploiement sur Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cvhevhpc1ekc73fuk4d0" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}"
