name: CI/CD Security Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Créer un environnement virtuel
        run: python -m venv venv

      - name: Activer l'environnement virtuel
        run: . venv/bin/activate

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Exécuter les tests
        run: python -m unittest test_app.py

  security:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer SonarQube Scanner
        run: |
          sudo apt-get update
          sudo apt-get install -y curl unzip
          curl -sS https://downloads.sonarsource.com/sonar-scanner/sonar-scanner-cli-4.6.2.2472-linux.zip -o sonar-scanner.zip
          unzip sonar-scanner.zip
          sudo mv sonar-scanner-4.6.2.2472-linux /opt/sonar-scanner
          sudo ln -s /opt/sonar-scanner/bin/sonar-scanner /usr/local/bin/sonar-scanner
          sonar-scanner \
            -Dsonar.organization=VOTRE_ORG \
            -Dsonar.projectKey=VOTRE_PROJET \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Installer Snyk et scanner les dépendances
        run: |
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --all-projects

      - name: Installer Trivy et scanner l’image Docker
        run: |
          sudo apt update && sudo apt install -y trivy
          docker build -t monapp .
          trivy image monapp

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Déclencher le déploiement sur Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cvhevhpc1ekc73fuk4d0?key=${{ secrets.RENDER_API_KEY }}"
