name: CI/CD Security Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Exécuter les tests
        run: python -m unittest test_app.py

  security:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3
        
      - name: Installer Java 17
        uses: actions/setup-java@v3
        with:
        distribution: 'temurin'
        java-version: '17'  
        
      - name: Installer SonarQube Scanner
        run: |
         wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
         unzip sonar-scanner.zip
         sudo mv sonar-scanner-4.7.0.2747-linux /opt/sonar-scanner
         echo "export PATH=\$PATH:/opt/sonar-scanner/bin" >> ~/.bashrc
         export PATH=$PATH:/opt/sonar-scanner/bin

      - name: Exécuter SonarQube Scanner
        run: |
          /opt/sonar-scanner/bin/sonar-scanner \
            -Dsonar.organization=VOTRE_ORG \
            -Dsonar.projectKey=VOTRE_PROJET \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Installer Snyk et scanner les dépendances
        run: |
          npm install -g snyk
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk test --all-projects

      - name: Installer Trivy et scanner l’image Docker
        run: |
          sudo apt update && sudo apt install -y trivy
          docker build -t monapp .
          trivy image monapp

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Déclencher le déploiement sur Render
        run: |
          curl -X POST "https://api.render.com/deploy/srv-cvhevhpc1ekc73fuk4d0?key=8-s1f-d5ymY"
